# Generated by Django 4.2.5 on 2024-01-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.URLField(max_length=700)),
                ("short_url", models.CharField(max_length=100)),
                ("time_data_created", models.DateTimeField()),
            ],
        ),
    ]
